# Generated by Django 4.0.3 on 2023-05-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_remove_question_likes'),
        ('pybo', '0013_alter_question_photo'),
    ]

    operations = [
    ]
